name: Build and Upload JAR to GitHub Releases

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/QA-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    defaults:
      run:
        working-directory: source/did-fabric-contract
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set release title
        id: set_release_title
        run: |
          release_tag=${GITHUB_HEAD_REF#release/QA-}
          echo "Release tag: $release_tag"
          echo "::set-output name=release_tag::$release_tag"

      - name: Get commit messages
        id: get_commit_messages
        run: |
          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"* %s")
          echo "$commits" > commit_messages.txt
          echo "::set-output name=commits::$commits"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.set_release_title.outputs.release_tag }}
          release_name: ${{ steps.set_release_title.outputs.release_tag }}
          body: |
            ## Changes:
            ${{ steps.get_commit_messages.outputs.commits }}